services:
  db:
    image: mariadb:11.4
    container_name: angau_db
    restart: always
    environment:
      MARIADB_DATABASE: angau
      MARIADB_ROOT_PASSWORD: root_password
      MARIADB_USER: user_angau
      MARIADB_PASSWORD: user_password
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:5.2
    platform: linux/amd64
    container_name: angau_pma
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
    depends_on:
      - db

volumes:
  db_data:
